development:
  host: localhost
  database: website_development

test:
  host: localhost
  database: website_test

# set these environment variables on your prod server
production:
  host: localhost
  database: website_development #use the same as testing for convenience
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
